### ISSUE TITLE
Configure() fails when using Tokens that do not require a login

### ISSUE THREAD

**Issue by jls5177** [eclipse-keypont/crypto11#46]
I noticed the latest v1.x changes now always attempts to login to the token regardless if the token states it requires a login or not. The previous code was checking this flag before calling login. 

There are a few proposals here:
1. Always perform the login and only error out when the `CKF_LOGIN_REQUIRED` flag is set on the token
1. Add a configuration field to optionally login to the token
1. Only login when the `TokenPin` is non-empty

**Reproduction Steps**
Select the module/accelerator token on a Thales HSM. This token does not require a login and will return an error code when we attempt to login.

**Comment by dmjones** [comment]
As a temporary solution, if you are blocked with an nShield HSM, there is an environment variable that allows you to "log in" to the accelerator token. Something like `CKA_FAKE_ACCELERATOR_LOGIN` (check the manual).

As for the solution, I prefer option 2.

Option 3 is risky, because you could legitimately have an empty PIN. I think Option 1 is risky due to the potential for libraries to interpret this differently.
